import './globals.css'
import { Lato } from 'next/font/google'

const lato = Lato({ subsets: ['latin'], weight: ["300", "400"] })

export const metadata = {
  title: 'Corrected Opinions',
  description: 'Correct version of correctopinions.info, generated by an LLM.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
